{{ $client := .IOSClient }}
{{ $name := .IOSClient.Name }}
{{ $domain := .IOSClient.BundleDomain }}
{{ $teamID := .IOSClient.TeamID }}
name: {{$name}}
settings:
  PRODUCT_BUNDLE_IDENTIFIER: {{$domain}}.$(PRODUCT_NAME)
  DEVELOPMENT_TEAM: {{$teamID}}
  IPHONEOS_DEPLOYMENT_TARGET: 11.0
targets:
  {{$name}}:
    type: application
    platform: iOS
    sources: Sources/{{$name}}
    {{if or $client.HasBackend $client.HasTests}}scheme:
      testTargets:{{if and $client.HasBackend $client.HasTests}}
      - {{$name}}KitTests{{end}}{{if $client.HasTests}}
      - {{$name}}UITests
      - {{$name}}Tests{{end}}
    {{if $client.HasBackend}}dependencies:
    - target: {{$name}}Kit{{end}}{{end}}
  
  {{if $client.HasTests}}{{$name}}Tests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/{{$name}}Tests
    dependencies:
    - target: {{$name}}
  
  {{$name}}UITests:
    type: bundle.ui-testing
    platform: iOS
    sources: Tests/{{$name}}UITests
    dependencies:
    - target: {{$name}}{{end}}
  
  {{if $client.HasBackend}}{{$name}}Kit:
    type: framework
    platform: iOS
    sources: Sources/{{$name}}Kit
    {{if $client.HasTests}}scheme:
      testTargets:
      - {{$name}}KitTests{{end}}{{end}}
  
  {{if and $client.HasBackend $client.HasTests}}{{$name}}KitTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/{{$name}}KitTests
    dependencies:
    - target: {{$name}}Kit{{end}}