name: {{.Name}}
settings:
  PRODUCT_BUNDLE_IDENTIFIER: co.nthn.$(PRODUCT_NAME)
  DEVELOPMENT_TEAM: {{.TeamID}}
targets:
  {{.Name}}:
    type: application
    platform: iOS
    sources: Sources/{{.Name}}
    {{if or .HasKit .HasTests .HasUITests}}scheme:
      testTargets:{{if and .HasKit .HasKit}}
      - {{.Name}}KitTests{{end}}{{if .HasUITests}}
      - {{.Name}}UITests{{end}}{{if .HasTests}}
      - {{.Name}}Tests{{end}}{{end}}
    {{if .HasKit}}dependencies:
    - target: {{.Name}}Kit{{end}}
  
  {{if .HasTests}}{{.Name}}Tests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/{{.Name}}Tests
    dependencies:
    - target: {{.Name}}{{end}}
  
  {{if .HasUITests}}{{.Name}}UITests:
    type: bundle.ui-testing
    platform: iOS
    sources: Tests/{{.Name}}UITests
    dependencies:
    - target: {{.Name}}{{end}}
  
  {{if .HasKit}}{{.Name}}Kit:
    type: framework
    platform: iOS
    sources: Sources/{{.Name}}Kit
    {{if .HasTests}}scheme:
      testTargets:
      - {{.Name}}KitTests{{end}}{{end}}
  
  {{if and .HasKit .HasTests}}{{.Name}}KitTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/{{.Name}}KitTests
    dependencies:
    - target: {{.Name}}Kit{{end}}